sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xiandan*19780815

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJKucGDTSptHqUMaNm6
    access-key-secret: SImboVg8yt9x1oEZRZZGkgxkkD9QjO
    bucket-name: insistentwind
  redis:
    host: localhost
    port: 6379
    database: 10

  wechat:
    appid: wx759d78c0a4073223
    secret: 3f5d9e10c5663760690a16d8a77f0ce6
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: http://23a48901.r7.cpolar.top/wxpay/pay.php
    refundNotifyUrl: http://23a48901.r7.cpolar.top/wxpay/pay.php